### ISSUE TITLE
roadmap

### ISSUE THREAD

**Issue by zxdong262** [zxdong262/rc-ai-bot#1]
- [ ] database??record bot subscribe info etc
- [x] credential file
- [x] invoke subscribe api
- [ ] user auth api
- [x] webhook event trigger api
- [x] glip messaging api
- [x] voicemail reader lib
- [x] voicemail transcript api[with goole open ai]

process:

1. develop user auth to subscribe new voicemail info to lamda
2. lamda subscribe and write sub info to db with current Glip Group Id
3. lamda get user auth info, write to db
4. lamda get voicemail webhook event
5. lamda fetch voicemail and transcript to text
6. lamda analysis text with goole ai
7. lamda send result to correct GlipId (even direct messages 1:1 conv have a groupId in Glip) using DbLookup for message store filter through glip api

**Comment by tylerlong** [comment]
For the following, you can check my code:

- webhook event trigger API
- glip messaging API
- user auth API
- invoke subscribe API

There are some code snippets for you to reference.


For Database, at this dev stage, we can just use a local JSON file as database.
